apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rando-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/Aransh/rando.git'
    targetRevision: HEAD
    path: helm/rando
    helm:
      valueFiles:
        - ../random.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: rando-app
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
    syncOptions:
    - CreateNamespace=true
